/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Lucas
 */
public class DatabasePanel extends javax.swing.JPanel {

    /**
     * Creates new form DatabasePanel
     */
    public DatabasePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionButtonGroup = new javax.swing.ButtonGroup();
        listsPanel = new javax.swing.JPanel();
        fieldsPanel = new javax.swing.JScrollPane();
        fieldsList = new javax.swing.JList<>();
        tablesPanel = new javax.swing.JScrollPane();
        tablesList = new javax.swing.JList<>();
        selectionPanel = new javax.swing.JPanel();
        selectionLabel = new javax.swing.JLabel();
        selectionButtonsPanel = new javax.swing.JPanel();
        singleButton = new javax.swing.JToggleButton();
        singleIntervalButton = new javax.swing.JToggleButton();
        multipleIntervalButton = new javax.swing.JToggleButton();

        setPreferredSize(new java.awt.Dimension(100000, 1000000));
        setLayout(new java.awt.GridLayout(2, 2, 15, 15));

        listsPanel.setLayout(new javax.swing.BoxLayout(listsPanel, javax.swing.BoxLayout.LINE_AXIS));

        fieldsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        fieldsPanel.setViewportView(fieldsList);

        listsPanel.add(fieldsPanel);

        tablesList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tablesPanel.setViewportView(tablesList);

        listsPanel.add(tablesPanel);

        add(listsPanel);

        selectionPanel.setLayout(new javax.swing.BoxLayout(selectionPanel, javax.swing.BoxLayout.PAGE_AXIS));

        selectionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectionLabel.setText("Modo de selección");
        selectionLabel.setAlignmentX(0.5F);
        selectionPanel.add(selectionLabel);

        selectionButtonsPanel.setAlignmentX(0.5F);

        selectionButtonGroup.add(singleButton);
        singleButton.setText("Simple");
        singleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selectionButtonsPanel.add(singleButton);

        selectionButtonGroup.add(singleIntervalButton);
        singleIntervalButton.setText("Por intervalo");
        singleIntervalButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selectionButtonsPanel.add(singleIntervalButton);

        selectionButtonGroup.add(multipleIntervalButton);
        multipleIntervalButton.setText("Múltiples intervalos");
        multipleIntervalButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selectionButtonsPanel.add(multipleIntervalButton);

        selectionPanel.add(selectionButtonsPanel);

        add(selectionPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> fieldsList;
    private javax.swing.JScrollPane fieldsPanel;
    private javax.swing.JPanel listsPanel;
    private javax.swing.JToggleButton multipleIntervalButton;
    private javax.swing.ButtonGroup selectionButtonGroup;
    private javax.swing.JPanel selectionButtonsPanel;
    private javax.swing.JLabel selectionLabel;
    private javax.swing.JPanel selectionPanel;
    private javax.swing.JToggleButton singleButton;
    private javax.swing.JToggleButton singleIntervalButton;
    private javax.swing.JList<String> tablesList;
    private javax.swing.JScrollPane tablesPanel;
    // End of variables declaration//GEN-END:variables
}
